In [1]:
import pandas as pd

In [2]:
df_athlete = pd.read_csv('/Users/augustincablant/Desktop/Kaggle/athlete_events.csv')
df_regions = pd.read_csv('/Users/augustincablant/Desktop/Kaggle/noc_regions.csv')
athle = df_athlete[df_athlete['Sport']=='Athletics'] 
athle['Event'].unique()
liste_athle = ["Athletics Men's 1,500 metres","Athletics Men's 5,000 metres","Athletics Men's 800 metres",
               "Athletics Men's 10,000 metres", "Athletics Women's 3,000 metres", "Athletics Men's 3,000 metres Steeplechase",
               "Athletics Women's 5,000 metres", "Athletics Women's 10,000 metres", "Athletics Women's 1,500 metres",
               "Athletics Women's 800 metres", "Athletics Women's 3,000 metres Steeplechase", 
               "Athletics Men's Cross-Country, Individual", "Athletics Men's 5 mile"]
athle[athle['Event'].isin(liste_athle)]

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
98,34,Jamale (Djamel-) Aarrass (Ahrass-),M,30.0,187.0,76.0,France,FRA,2012 Summer,2012,Summer,London,Athletics,"Athletics Men's 1,500 metres",NaN
148,55,Antonio Abadia Beci,M,26.0,170.0,65.0,Spain,ESP,2016 Summer,2016,Summer,Rio de Janeiro,Athletics,"Athletics Men's 5,000 metres",NaN
190,86,Jos Manuel Abascal Gmez,M,22.0,182.0,67.0,Spain,ESP,1980 Summer,1980,Summer,Moskva,Athletics,"Athletics Men's 1,500 metres",NaN
191,86,Jos Manuel Abascal Gmez,M,26.0,182.0,67.0,Spain,ESP,1984 Summer,1984,Summer,Los Angeles,Athletics,"Athletics Men's 1,500 metres",Bronze
241,117,Maher Abbas,M,22.0,178.0,78.0,Lebanon,LIB,1988 Summer,1988,Summer,Seoul,Athletics,Athletics Men's 800 metres,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
270809,135437,"Mara Teresa ""Maite"" Ziga Domnguez",F,31.0,167.0,55.0,Spain,ESP,1996 Summer,1996,Summer,Atlanta,Athletics,"Athletics Women's 1,500 metres",NaN
270912,135480,Geeta Zutshi,F,23.0,167.0,51.0,India,IND,1980 Summer,1980,Summer,Moskva,Athletics,Athletics Women's 800 metres,NaN
270913,135480,Geeta Zutshi,F,27.0,167.0,51.0,India,IND,1984 Summer,1984,Summer,Los Angeles,Athletics,"Athletics Women's 3,000 metres",NaN
271027,135531,Sabine Beate Zwiener (-Jauchstetter),F,24.0,172.0,52.0,Germany,GER,1992 Summer,1992,Summer,Barcelona,Athletics,Athletics Women's 800 metres,NaN
271044,135543,"Victor Andrew ""Vic"" Zwolak",M,25.0,175.0,64.0,United States,USA,1964 Summer,1964,Summer,Tokyo,Athletics,"Athletics Men's 3,000 metres Steeplechase",NaN